setwd("C:/Users/Tong/Desktop/Coursera/data")
household_data <- read.table("household_power_consumption.txt",sep = ";",header = FALSE,col.names = c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3"),na.strings ="?",skip = grep("31/1/2007",readLines("household_power_consumption.txt")),nrows = 4319)
household_data <- subset(household_data,Date %in% c("1/2/2007","2/2/2007"))
household_data$DateTime <- as.POSIXct(strptime(paste(household_data$Date,household_data$Time,sep = " "),format = "%e/%m/%Y %H:%M:%S"))
Sys.setlocale("LC_ALL","English")
png("plot2.png",width = 480, height = 480)
with(household_data,plot(DateTime,Global_active_power,ylab = "Global Active Power (kilowatts)",xlab = "",type = "n"))
with(household_data,lines(DateTime,Global_active_power))
dev.off()