setwd("C:/Users/Tong/Desktop/Coursera/data")
household_data <- read.table("household_power_consumption.txt",sep = ";",header = FALSE,col.names = c("Date","Time","Global_active_power","Global_reactive_power","Voltage","Global_intensity","Sub_metering_1","Sub_metering_2","Sub_metering_3"),na.strings ="?",skip = grep("31/1/2007",readLines("household_power_consumption.txt")),nrows = 4319)
household_data <- subset(household_data,Date %in% c("1/2/2007","2/2/2007"))
household_data$DateTime <- as.POSIXct(strptime(paste(household_data$Date,household_data$Time,sep = " "),format = "%e/%m/%Y %H:%M:%S"))
Sys.setlocale("LC_ALL","English")
png("plot4.png",width = 480, height = 480)
par(mfcol = c(2,2))
with(household_data,{plot(DateTime,Global_active_power,ylab = "Global Active Power (kilowatts)",xlab = "",type = "n")
  lines(DateTime,Global_active_power)})
with(household_data,{plot(DateTime,Sub_metering_1,ylab = "Energy Sub metering",xlab = "",type = "n")
      lines(DateTime,Sub_metering_1,col = "black")
      lines(DateTime,Sub_metering_2,col = "red")
      lines(DateTime,Sub_metering_3,col = "blue")
      legend("topright",pch = "_", col = c("black","red","blue"),legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))})
with(household_data,{plot(DateTime,Voltage,ylab = "Voltage",xlab = "",type = "n")
  lines(DateTime,Voltage)})
with(household_data,{plot(DateTime,Global_reactive_power,ylab = "Global Reactive Power",xlab = "",type = "n")
  lines(DateTime,Global_reactive_power)})
dev.off()